-- MySQL Script generated by MySQL Workbench
-- Fri Nov 28 14:31:33 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema marathon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'auto incrementing user_id of each user, unique index',
  `user_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'user\'s name, unique',
  `user_password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'user\'s password in salted and hashed format',
  `user_email` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'user\'s email, unique',
  `user_active` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'user\'s activation status',
  `user_account_type` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'user\'s account type (basic, premium, etc)',
  `user_rememberme_token` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'user\'s remember-me cookie token',
  `user_creation_timestamp` BIGINT(20) NULL DEFAULT NULL COMMENT 'timestamp of the creation of user\'s account',
  `user_last_login_timestamp` BIGINT(20) NULL DEFAULT NULL COMMENT 'timestamp of user\'s last login',
  `user_failed_logins` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'user\'s failed login attempts',
  `user_last_failed_login` INT(10) NULL DEFAULT NULL COMMENT 'unix timestamp of last failed login attempt',
  `user_activation_hash` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'user\'s email verification hash string',
  `user_password_reset_hash` CHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'user\'s password reset code',
  `user_password_reset_timestamp` BIGINT(20) NULL DEFAULT NULL COMMENT 'timestamp of the password reset request',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name` (`user_name` ASC),
  UNIQUE INDEX `user_email` (`user_email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'user data';


-- -----------------------------------------------------
-- Table `etape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etape` ;

CREATE TABLE IF NOT EXISTS `etape` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `debut` DATE NOT NULL,
  `fin` DATE NOT NULL,
  `ordre` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `id_voyage` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_etape_voyage_idx` (`id_voyage` ASC),
  CONSTRAINT `FK_etape_voyage`
    FOREIGN KEY (`id_voyage`)
    REFERENCES `voyage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `media` ;

CREATE TABLE IF NOT EXISTS `media` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `format` VARCHAR(45) NOT NULL,
  `id_etape` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_media_etape_idx` (`id_etape` ASC),
  CONSTRAINT `FK_media_etape`
    FOREIGN KEY (`id_etape`)
    REFERENCES `etape` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `voyage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voyage` ;

CREATE TABLE IF NOT EXISTS `voyage` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `en_ligne` TINYINT(1) NOT NULL DEFAULT '0',
  `id_media_titre` INT(11) NULL DEFAULT NULL,
  `id_auteur` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_voyage_utilisateur_idx` (`id_auteur` ASC),
  INDEX `FK_voyage_media_titre_idx` (`id_media_titre` ASC),
  CONSTRAINT `FK_voyage_utilisateur`
    FOREIGN KEY (`id_auteur`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_voyage_media_titre`
    FOREIGN KEY (`id_media_titre`)
    REFERENCES `media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commentaire` ;

CREATE TABLE IF NOT EXISTS `commentaire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_personne` INT(11) NOT NULL,
  `id_voyage` INT(11) NOT NULL,
  `contenu` TEXT NOT NULL,
  `date_post` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `evaluation` ENUM('0','1','2','3','4','5') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Commentaire_personne_idx` (`id_personne` ASC),
  INDEX `FK_commentaire_voyage_idx` (`id_voyage` ASC),
  CONSTRAINT `FK_Commentaire_personne`
    FOREIGN KEY (`id_personne`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_commentaire_voyage`
    FOREIGN KEY (`id_voyage`)
    REFERENCES `voyage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
